### ISSUE TITLE
SemiCVT

### ISSUE THREAD

**Issue by XZNWU** [zerone-fg/SemiCVT#1]
I can't find the "SemiCVT: Semi-Supervised Convolutional Vision Transformer for Semantic Segmentation" article on the Internet, so I don't know the specific details of the plan. Can you share the article this code refers to?

**Comment by zerone-fg** [comment]
Thank you for your attention, our paper is accepted by CVPR2023 recently, but we haven't published the article yet. And we will publish it after camera ready and the code will be available officially at that time. Thank you.
